name: build-and-deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  APP_NAME: eg-hackathon23-blr-birbalbot
  REGISTRY: kumo-docker-release-local.artylab.expedia.biz

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ eg-default ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # This step Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      # Build
      - name: Build
        run: |
          chmod 755 ./build.sh
          ./build.sh

      # Docker Setup
      - name: Docker login
        uses: actions/docker-login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_PASS }}

      # Docker Build & Publish
      - name: Build and push docker image
        uses: actions/docker-build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/library/${{ env.APP_NAME }}:${{ github.sha }}

      # Trigger Spinnaker Pipeline
      - name: Trigger Spinnaker pipeline
        uses: actions/spinnaker-pipeline-trigger@v1
        with:
          topic_arn: arn:aws:sns:us-west-2:584472815078:spinnaker-github-actions
